export const LOAD_DEFAULT_FOREX_DATA_SUCCESS = 'LOAD_DEFAULT_FOREX_DATA_SUCCESS'

export const LOAD_CURRENCY_DATUM_SUCCESS = 'LOAD_CURRENCY_DATUM_SUCCESS'

export const CLEAR_FOREX_DATA_SUCCESS = 'CLEAR_FOREX_DATA_SUCCESS'

export const CLEAR_CURRENCY_DATUM_SUCCESS = 'CLEAR_CURRENCY_DATUM_SUCCESS'
